# SITE CONFIGURATION
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://jedelman.com" # the base hostname & protocol for your site

permalink: /home/:title/
# THEME-SPECIFIC CONFIGURATION
orig_theme:
  # Meta
  title: Jason Edelman's Blog
  #avatar: avatar.png
  #gravatar: # email md5 hash
  description: "Focused on networking, from the past to the present: SDN, Automation, and DevOps." # used by search engines

  # Header and footer text
  header_text: >
     <p>Welcome to the new Blog.</p>

     <p>Curently under construction. Please be patient during the migration.  Posts from 2012 and 2013 are coming soon!</p>
  footer_text: >
   <form style="border:1px solid #fff;padding:3px;text-align:center;" action="http://feedburner.google.com/fb/a/mailverify" method="post" target="popupwindow" onsubmit="window.open('http://feedburner.google.com/fb/a/mailverify?uri=JasonEdelmanjedelman8', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true"><p>Subscribe to this Blog by Email:</p><p><input type="text" style="width:190px" name="email"/></p><input type="hidden" value="JasonEdelmanjedelman8" name="uri"/><input type="hidden" name="loc" value="en_US"/><input type="submit" value="Enter Your Email Adress" /></form>



  #Powered by <a href="http://jekyllrb.com">Jekyll</a> and <a href="https://pages.github.com">Git Hub Pages</a>

  # Icons
  rss: true
  email_address: jedelman8@gmail.com
  github: "jedelman8"
  linkedin: "https://www.linkedin.com/in/jedelman8"# full URL
  twitter: "jedelman8"
  youtube: "jedelman23"

  # Scripts
  google_analytics: UA-37434033-1
  disqus_shortname: jedelman8

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 20
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Jason Edelman
  email: jedelman8@gmail.com
  github: jedelman8
  twitter: jedelman8

